services:
  carInventory:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: carService
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
  bookingService:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: bookingService
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: postgres
    ports:
      - "5435:5432"
  paymentService:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: paymentService
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: postgres
    ports:
      - "5436:5432"

  customerService:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: customerService
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: postgres
    ports:
      - "5437:5432"


  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"

#services:
#  carInventory:
#    image: 'postgres:latest'
#    environment:
#      POSTGRES_DB: CarInventory
#      POSTGRES_PASSWORD: sample
#      POSTGRES_USER: postgres
#   ports:
#      - "5434:5434"

#  carService:
#    image: 'postgres:latest'
#    environment:
#      POSTGRES_DB: CarService
#      POSTGRES_PASSWORD: sample
#      POSTGRES_USER: postgres
#    ports:
#      - "5432:5432"




  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:latest'
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.2
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.yml:/etc/datasource/datasource.yml
