global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: carInventory
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: 'Car Inventory Application'
  #          - '192.168.1.14:8081'

  - job_name: bookingService
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          application: 'Booking Service Application'

  - job_name: customerService
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8084"]
        labels:
          application: 'Customer Service Application'

  - job_name: paymentService
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]
        labels:
          application: 'Payment Service Application'