global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: carInventory
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["carInventory:8081"]
        labels:
          application: 'Car Inventory Application'
#          - '192.168.1.14:8081'